image: eclipse-temurin:18-jdk

scan-code:
  stage: .pre
  image:
    name: "zricethezav/gitleaks:latest"
    entrypoint: [ "" ]
  script:
    - gitleaks detect --verbose --redact --no-git --source="$CI_PROJECT_DIR"
  tags:
    - docker

test-code:
  stage: test
  script:
    - suffix=$([[ $(uname -m) == "aarch64" ]] && echo "arm64" || echo "x86-64")
    - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_$suffix
    - chmod +x agent
    - ./agent &
    - ./agent wait
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - docker
