image: eclipse-temurin:19-jdk

test_code:
  stage: test
  script:
    - suffix=$([[ $(uname -m) == "aarch64" ]] && echo "arm64" || echo "x86-64")
    - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_$suffix
    - chmod +x agent
    - ./agent &
    - ./agent wait
    - chmod +x gradlew
    - ./gradlew jacocoTestReport
    - cat build/reports/jacoco/test/html/index.html
  tags:
    - docker
