# DinD (Docker in Docker) service is required for Testcontainers
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

## job test_code
## - run unit tests
test_code:
  image: gradle:6.5.1
  stage: test
  script:
    - sh ./gradlew test
  tags:
    - DOCKER
