before_install:
  - chmod +x gradlew

language: java
install: true
jdk: openjdk17

script:
  - curl -L -o agent https://app.testcontainers.cloud/download/testcontainers-cloud-agent_linux_x86-64
  - chmod +x agent
  - ./agent &
  - ./agent wait
  - ./gradlew jacocoTestReport sonarqube

notifications:
  email:
    recipients:
      - hugo.rad@gmail.com
    on_success: always
    on_failure: always
