# Build java application for presenting gathered sprint statistics data

before_install:
  # Set Gradle builder executable permissions
  - chmod +x gradlew

language: java
install: true
jdk: openjdk11

script:
  # Use Gradle as tester
  - ./gradlew test

