version: '3.5'

## Services
services:
  sprint_stats_db:
    image: mysql:8.0.31
    container_name: sprint_stats_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sprints
      MYSQL_PASSWORD: sprints
      MYSQL_DATABASE: sprints
    volumes:
      - dbdata:/var/lib/mysql/

#Volumes
volumes:
  dbdata:
    driver: local
