version: '3.5'

## Services
services:
  viewer:
    build: .
    image: sprint-stats-viewer
    ports:
      - "8087:5000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/sprints?useSSL=false
      - SPRING_DATASOURCE_USERNAME=sprints
      - SPRING_DATASOURCE_PASSWORD=sprints
    networks:
      - sprintnet

  #MySQL Service
  db:
    image: mysql:5.7.29
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sprints
      MYSQL_PASSWORD: sprints
      MYSQL_DATABASE: sprints
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - sprintnet

#Networks
networks:
  sprintnet:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local

