version: '3.5'

## Services
services:
  #MySQL Service
  sprint_stats_db:
    image: mysql:5.7.29
    container_name: sprint_stats_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sprints
      MYSQL_PASSWORD: sprints
      MYSQL_DATABASE: sprints
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - sprintnet

#Networks
networks:
  sprintnet:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
